/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as TermsRouteImport } from './routes/terms';
import { Route as PrivacyRouteImport } from './routes/privacy';
import { Route as MyPredictionsRouteImport } from './routes/my-predictions';
import { Route as LeaderboardRouteImport } from './routes/leaderboard';
import { Route as IndexRouteImport } from './routes/index';
import { Route as RacesIndexRouteImport } from './routes/races/index';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as RacesRaceIdRouteImport } from './routes/races/$raceId';
import { Route as AdminRacesNewRouteImport } from './routes/admin/races/new';
import { Route as AdminRacesRaceIdRouteImport } from './routes/admin/races/$raceId';

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any);
const MyPredictionsRoute = MyPredictionsRouteImport.update({
  id: '/my-predictions',
  path: '/my-predictions',
  getParentRoute: () => rootRouteImport,
} as any);
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any);
const RacesRaceIdRoute = RacesRaceIdRouteImport.update({
  id: '/races/$raceId',
  path: '/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRacesNewRoute = AdminRacesNewRouteImport.update({
  id: '/admin/races/new',
  path: '/admin/races/new',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRacesRaceIdRoute = AdminRacesRaceIdRouteImport.update({
  id: '/admin/races/$raceId',
  path: '/admin/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/leaderboard': typeof LeaderboardRoute;
  '/my-predictions': typeof MyPredictionsRoute;
  '/privacy': typeof PrivacyRoute;
  '/terms': typeof TermsRoute;
  '/races/$raceId': typeof RacesRaceIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/races/': typeof RacesIndexRoute;
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute;
  '/admin/races/new': typeof AdminRacesNewRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/leaderboard': typeof LeaderboardRoute;
  '/my-predictions': typeof MyPredictionsRoute;
  '/privacy': typeof PrivacyRoute;
  '/terms': typeof TermsRoute;
  '/races/$raceId': typeof RacesRaceIdRoute;
  '/admin': typeof AdminIndexRoute;
  '/races': typeof RacesIndexRoute;
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute;
  '/admin/races/new': typeof AdminRacesNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/leaderboard': typeof LeaderboardRoute;
  '/my-predictions': typeof MyPredictionsRoute;
  '/privacy': typeof PrivacyRoute;
  '/terms': typeof TermsRoute;
  '/races/$raceId': typeof RacesRaceIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/races/': typeof RacesIndexRoute;
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute;
  '/admin/races/new': typeof AdminRacesNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/my-predictions'
    | '/privacy'
    | '/terms'
    | '/races/$raceId'
    | '/admin/'
    | '/races/'
    | '/admin/races/$raceId'
    | '/admin/races/new';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/leaderboard'
    | '/my-predictions'
    | '/privacy'
    | '/terms'
    | '/races/$raceId'
    | '/admin'
    | '/races'
    | '/admin/races/$raceId'
    | '/admin/races/new';
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/my-predictions'
    | '/privacy'
    | '/terms'
    | '/races/$raceId'
    | '/admin/'
    | '/races/'
    | '/admin/races/$raceId'
    | '/admin/races/new';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LeaderboardRoute: typeof LeaderboardRoute;
  MyPredictionsRoute: typeof MyPredictionsRoute;
  PrivacyRoute: typeof PrivacyRoute;
  TermsRoute: typeof TermsRoute;
  RacesRaceIdRoute: typeof RacesRaceIdRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  RacesIndexRoute: typeof RacesIndexRoute;
  AdminRacesRaceIdRoute: typeof AdminRacesRaceIdRoute;
  AdminRacesNewRoute: typeof AdminRacesNewRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms';
      path: '/terms';
      fullPath: '/terms';
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy': {
      id: '/privacy';
      path: '/privacy';
      fullPath: '/privacy';
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/my-predictions': {
      id: '/my-predictions';
      path: '/my-predictions';
      fullPath: '/my-predictions';
      preLoaderRoute: typeof MyPredictionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/leaderboard': {
      id: '/leaderboard';
      path: '/leaderboard';
      fullPath: '/leaderboard';
      preLoaderRoute: typeof LeaderboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/races/': {
      id: '/races/';
      path: '/races';
      fullPath: '/races/';
      preLoaderRoute: typeof RacesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/races/$raceId': {
      id: '/races/$raceId';
      path: '/races/$raceId';
      fullPath: '/races/$raceId';
      preLoaderRoute: typeof RacesRaceIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/races/new': {
      id: '/admin/races/new';
      path: '/admin/races/new';
      fullPath: '/admin/races/new';
      preLoaderRoute: typeof AdminRacesNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/races/$raceId': {
      id: '/admin/races/$raceId';
      path: '/admin/races/$raceId';
      fullPath: '/admin/races/$raceId';
      preLoaderRoute: typeof AdminRacesRaceIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyPredictionsRoute: MyPredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  RacesRaceIdRoute: RacesRaceIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  RacesIndexRoute: RacesIndexRoute,
  AdminRacesRaceIdRoute: AdminRacesRaceIdRoute,
  AdminRacesNewRoute: AdminRacesNewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
